C_Web/C_Web/Areas/WebCAdmin/Controllers/SYSListController.cs
using Microsoft.AspNetCore.Mvc;
using Web_SYSList_Services;
using C_WebDTO.CommonDTO;
using C_Web.Entity.SYS;
using C_Web.Extension;
using C_WebDTO.SessionDTO;
using System.Data.Entity.ModelConfiguration.Configuration;

namespace C_Web.Areas.WebCAdmin.Controllers
{
    [Area("WebCAdmin")]
    public class SYSListController : Controller
    {
        private readonly ISYSList_Services _ISYSList_Services;
        public SYSListController(ISYSList_Services _ISYSList_Services)
        {
            this._ISYSList_Services = _ISYSList_Services;
        }
        public IActionResult Index(long? SYSListId=null)
        {
            if(SYSListId == null)
            {
                return View();
            }
            else
            {
                ViewBag.FAname = "上層功能：" +  _ISYSList_Services.GetFatherName(SYSListId);
                ViewBag.SYSListId= SYSListId;
                return View();
            }
            
        }
        public IActionResult CreateSYSListModal(long? SYSListId=null)
        {
            ViewBag.SYSListId = SYSListId;
            return PartialView("_Create");
        }
        public IActionResult EditSYSListModal(long Id)
        {
            SYS_List model = _ISYSList_Services.GetEditModel(Id);
            if (model == null)
                model = new SYS_List();
            return PartialView("_Edit", model);
        }
        [HttpPost]
        public IActionResult ViewSYSListTable(int? SYSListId=null)
        {
            DataTableDTO data = new()
            {
                data = _ISYSList_Services.GetSYSListTable(SYSListId)
            };
            return Json(data);
        }
        [HttpPost]
        public IActionResult CreateSYSList([FromBody] FetchDTO ListModel)  
        {
            ListModel.MUser = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            if (_ISYSList_Services.CreateSYSList(ListModel))
                return Json(new { Success = true });
            else
                return Json(new { Success = false });
        }
        [HttpPost]
        public IActionResult EditSYSList([FromBody] SYS_List ListModel)
        {
            ListModel.MUser = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            if (_ISYSList_Services.EditSYSList(ListModel))
                return Json(new { Success = true });
            else
                return Json(new { Success = false });
        }
        [HttpPost]
        public IActionResult EditOnOff([FromBody] FetchDTO DTO)
        {
            if (_ISYSList_Services.OnOff(DTO))
                return Json(new { Success = true });
            else
                return Json(new { Success = false });
        }
        [HttpPost]
        public IActionResult ViewOrder([FromBody] FetchDTO DTO)
        {
            if(DTO.data.Length > 0)
            {
                if(_ISYSList_Services.SYSListOrder(DTO.data, DTO.order))
                    return Json(new { Success = true });
                else
                    return Json(new { Success = false });
            }
            else
                return Json(new { Success = false }); ;
        }
    }
}

C_Web/C_Web/Areas/WebCAdmin/Views/SYSList/Index.cshtml
@using C_Web.Extension



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav">
                    <li>
                        <button class="btn btn-primary" id="createmodal">新 增</button>
                        <button id="back" class="btn btn-dark">返 回</button>
                    </li>
                </ul>
            </div>
            <hr />
            <h2>
                <font style="font-size:20px; color:#475A70;">@ViewBag.FAname</font>
                <input id="syslistID" style="display:none" value="@ViewBag.SYSListId" readonly hidden />
            </h2>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <table class="table-bordered table-hover dt-center table nowrap syslistTable con10" id="syslistTable">
                        <thead>
                            <tr style="text-align: center;">
                                <th nowrap data-priority="1"><a class="btn btn-info btn-sm" role="button" id="OrderUpdate" style="color: white">更新排序</a></th>
                                <th nowrap data-priority="3">啟用狀態</th>
                                <th nowrap data-priority="4">功能名稱</th>
                                <th nowrap data-priority="5">更新人員</th>
                                <th nowrap data-priority="6">更新時間</th>
                                <th nowrap data-priority="2"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!--Create Modal-->
    <div class="modal fade" id="CreateSYSList" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <!--Edit Modal-->
    <div class="modal fade" id="EditSYSList" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        datatablemenu("#syslistTable", { SYSListId: $("#syslistID").val() });
    });

    //#region y軸拖曳效果
    $(document).ready(function () {
        var fixHelper = function (e, ui) {
            ui.children().each(function () {
                $(this).width($(this).width());
            });
            return ui;
        };
        $(function () {
            $("tbody").sortable({
                helper: fixHelper,
                axis: "y"
            }).disableSelection();
            $('tbody td').not('.dtr-control').mousedown(function (event) {
                event.stopImmediatePropagation();
            });
        });
    });
    //#endregion

    //#region datatable
    function datatablemenu() { 
        $("#syslistTable").DataTable({
            "processing": true,
            "bServerSide": true,
            "destroy": true,
            "order": [[0, "asc"]],
            "pageLength": "10",
            "lengthMenu": [[10, 20, 30, 40, -1], [10, 20, 30, 40, "All"]],
            "paging": false,
            "searching": false,
            "bJQueryUI": true,
            "autoWidth": true,
            "ajax": {
                "url": "@Url.Action("ViewSYSListTable","SYSList")",
                "type": "POST",
                "data": { SYSListId: $("#syslistID").val() },
            },
            "columns": [
                { 
                    "targets": 0, "data": null, "name": "Orders", "render": function (source) {
                        let html = "";
                        html += `<i class="bi bi-arrows-move" data-value=`+ source.orderint+`></i>`;
                        return html;
                    }
                },
                {
                    "targets": 2, "data": null, "name": "OnOff", "render": function (source) {
                        let html = "";
                        if (source.booldata) {
                            html += `<input value="` + source.pkId + `" class="Onoff" id="onoff" type="checkbox" checked/>`;
                        } else {
                            html += `<input value="` + source.pkId + `" class="Onoff" id="onoff" type="checkbox" />`;
                        }
                        html += `<input id="childid" style="display:none;" value="` + source.pkId + `" data_order="` + source.orderint + `"/>`;
                        return html;
                    }
                },
                { "targets": 3, "data": "text1", "name": "Name" },
                { "targets": 4, "data": "text4", "name": "MUser" },
                { "targets": 5, "data": "text5", "name": "MTime" },
                {
                    "targets": 1, "data": null, "orderable": false, "render": function (source) {
                        let html = "";
                        // html += `<a class="btn btn-success btnDetail mr-2" role="button" style="color: white" href="/WebCAdmin/SYSList/EditSYSListModal?Id=` + source.pkId + `">編 輯</a>`;
                        html += `<button class="btn btn-success btnedit mr-2" role="button" style="color: white" value="` + source.pkId + `">編 輯</button>`;
                        html += `<a class="btn btn-primary mr-2" role="button" style="color: white" href="/WebCAdmin/SYSList/Index?SYSListId=` + source.pkId + `">子項目</a>`
                        return html;
                    },
                },
            ],
            "drawCallback": function () {
                $("[id=onoff]").bootstrapToggle({
                    on: "啟用",
                    off: "停用",
                    onstyle: "info",
                    width: 100,
                });
                $(".btnedit").on("click", function () {
                    $("#EditSYSList .modal-content").load("@Url.Action("EditSYSListModal", "SYSList")", { Id: $(this).val() });
                    $("#EditSYSList").modal("show");
                });
                $(".Onoff").on("change", function () {
                    var id = $(this).val();
                    var checked = $(this).is(":checked");
                    OnOff(id, checked);
                });
            },
            responsive: true
        });
    };
    //#endregion

    //#region 排序更新
    $("#OrderUpdate").on("click", function () { 
        var targets = $("input[id=childid]");
        var strings = [], strings2 = [];
        var i = 1;
        $.map(targets, function (d) {
            strings.push(parseInt(d.value));
            strings2.push(parseInt(i));
            i++;
            if (strings.length == targets.length) {
                fetch("@Url.Action("ViewOrder", "SYSList")", {
                    method: "POST",
                    body: JSON.stringify({
                        data: strings,
                        order: strings2,
                    }),
                    headers: new Headers({
                        "Content-Type": "application/json",
                    }),
                })
                .then((res) => {
                    return res.json();
                }).then((resjson) => {
                    if (resjson.success) {
                        $("#CreateSYSList").modal("hide");
                        datatablemenu("#syslistTable", {});
                        Swal.fire({
                            icon: "success",
                            title: "成功",
                            text: "排序完成",
                            showCloseButton: true,
                            backdrop: true,
                        });
                    }
                    else {
                        Swal.fire({
                            icon: "error",
                            title: "失敗",
                            text: "排序錯誤",
                            showCloseButton: true,
                            backdrop: true,
                        })
                    }
                })
            }
        });
    })
    //#endregion

    //#region 狀態開關
    function OnOff(id, bool) {
        fetch("@Url.Action("EditOnOff", "SYSList")", {
            method: "POST",
            body: JSON.stringify({
                PKId: id,
                OnOff: bool,
            }),
            headers: new Headers({
                "Content-Type": "application/json",
            }),
        })
        .then((res) => {
            console.log(res);
            return res.json();
        }).then((resjson) => {
            if (resjson.success) {
                $("#CreateSYSList").modal("hide");
                datatablemenu("#syslistTable", {});
                Swal.fire({
                    icon: "success",
                    title: "成功",
                    text: "狀態變更完成",
                    showCloseButton: true,
                    backdrop: true,
                });
            }
            else {
                Swal.fire({
                    icon: "error",
                    title: "失敗",
                    text: "狀態變更錯誤",
                    showCloseButton: true,
                    backdrop: true,
                })
            }
        })
    }
    //#endregion

    $("#back").on('click', function () {
        window.history.back();
    });

    $("#createmodal").on("click", function () { 
        $("#CreateSYSList .modal-content").load("@Url.Action("CreateSYSListModal", "SYSList")", { SYSListId: $("#syslistID").val() });
        $("#CreateSYSList").modal("show");
    })
</script>

C_Web/C_Web/Areas/WebCAdmin/Views/SYSList/_Create.cshtml
@model C_Web.Entity.SYS.SYS_List

<div class="modal-header">
    <h2 class="modal-title">
        新增子系統
    </h2>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="modal-body">
    @* @Html.HiddenFor(x => x.FAID, new{ value=ViewBag.SYSListId }) *@
    <input id="FAID" name="FAID" value="@ViewBag.SYSListId" type="hidden" />
    <div class="form-group">
        <input name="Name" id="Name" placeholder="輸入功能名稱" class="form-control" />
        <span id="errorname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input name="Url" id="Url" placeholder="輸入導向網址" class="form-control" />
        <span id="errorurl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input name="Icon" id="Icon" placeholder="輸入圖示" class="form-control" />
    </div>
</div>

<div class="modal-footer">
    <button type="button" id="createsyslist" class="btn btn-primary btn-sm">新增</button>
</div>


<script>
    //#region create
    $("#createsyslist").on("click", function () {
        if ($("#Name").val() == "" || $("#Url").val() == ""){
            if ($("#Name").val() == "") 
                $("#errorname").html("請輸入功能名稱");
            else
                $("#errorname").html("");
            if ($("#Url").val() == "") 
                $("#errorurl").html("請輸入導向網址");
            else
                $("#errorurl").html("");
            return false
        }
        else {
            fetch("@Url.Action("CreateSYSList", "SYSList")", {
                method: "POST",
                body: JSON.stringify({
                    Name: $("#Name").val(),
                    Url: $("#Url").val(),
                    Icon: $("#Icon").val(),
                    FAID: $("#FAID").val(),
                }),
                headers: new Headers({
                    "Content-Type": "application/json",
                }),
            })
            .then((res) => {
                return res.json();
            }).then((resjson) => {
                if (resjson.success) {
                    $("#CreateSYSList").modal("hide");
                    datatablemenu("#syslistTable", {});
                    Swal.fire({
                        icon: "success",
                        title: "成功",
                        text: "新增完成",
                        showCloseButton: true,
                        backdrop: true,
                    });
                }
                else {
                    Swal.fire({
                        icon: "error",
                        title: "失敗",
                        text: "新增錯誤",
                        showCloseButton: true,
                        backdrop: true,
                    })
                }
            })
        }
    })
    //#endregion

</script>

C_Web/C_Web/Areas/WebCAdmin/Views/SYSList/_Edit.cshtml
@model C_Web.Entity.SYS.SYS_List

<div class="modal-header">
    <h2 class="modal-title">
        修改子系統
    </h2>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<div class="modal-body">
   @Html.HiddenFor(x => x.SYSListId)
@Html.HiddenFor(x => x.FAID)
<div class="form-group">
    <input value="@Model.Name" name="Name" id="Name" placeholder="輸入功能名稱" class="form-control" />
    <span id="errorname" class="text-danger"></span>
</div>
<div class="form-group">
    <input value="@Model.Url" name="Url" id="Url" placeholder="輸入導向網址" class="form-control" />
    <span id="errorurl" class="text-danger"></span>
</div>
<div class="form-group">
    <input value="@Model.Icon" name="Icon" id="Icon" placeholder="輸入圖示" class="form-control" />
</div>
</div>

<div class="modal-footer">
    <button type="button" id="editsyslist" class="btn btn-primary btn-sm">修 改</button>
</div>


<script>
    //#region edit
    $("#editsyslist").on("click", function () {
        if ($("#Name").val() == "" || $("#Url").val() == "") {
            if ($("#Name").val() == "")
                $("#errorname").html("請輸入功能名稱");
            else
                $("#errorname").html("");
            if ($("#Url").val() == "")
                $("#errorurl").html("請輸入導向網址");
            else
                $("#errorurl").html("");
            return false
        }
        else {
            fetch("@Url.Action("EditSYSList", "SYSList")", {
                method: "POST",
                body: JSON.stringify({
                    Name: $("#Name").val(),
                    Url: $("#Url").val(),
                    Icon: $("#Icon").val(),
                    SYSListId: $("#SYSListId").val(),
                }),
                headers: new Headers({
                    "Content-Type": "application/json",
                }),
            })
                .then((res) => {
                    return res.json();
                }).then((resjson) => {
                    if (resjson.success) {
                        $("#EditSYSList").modal("hide");
                        datatablemenu("#syslistTable", {});
                        Swal.fire({
                            icon: "success",
                            title: "成功",
                            text: "修改完成",
                            showCloseButton: true,
                            backdrop: true,
                        });
                    }
                    else {
                        Swal.fire({
                            icon: "error",
                            title: "失敗",
                            text: "修改錯誤",
                            showCloseButton: true,
                            backdrop: true,
                        })
                    }
                })
        }
    })
    //#endregion

</script>