C_Web/C_Web/Areas/TrackSpending/Controllers/TrackSpendController.cs
using C_Web.Entity.TrackSpend;
using C_Web.Entity.TrackSpend.Enum;
using C_Web.Extension;
using C_WebDTO.SessionDTO;
using C_WebDTO.TrackSpendDTO;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Web_TrackSpend_Services;
using WebC.Generic.Repository;

namespace C_Web.Areas.TrackSpending.Controllers
{
    [Area("TrackSpending")]
    public class TrackSpendController : Controller
    {
        private readonly ITrackSpend_Services _ITrackSpend_Services;
        public TrackSpendController(ITrackSpend_Services _ITrackSpend_Services)
        {
            this._ITrackSpend_Services = _ITrackSpend_Services;
        }
        public IActionResult Index(string? nowdate)
        {
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            if (nowdate == null)
                nowdate = DateTime.Now.Month.ToString();
            else
                nowdate = nowdate.Split("-")[1];
            List<TrackSpendDTO> tracks = _ITrackSpend_Services.GetTracks(UserId, nowdate);
            ViewBag.data = _ITrackSpend_Services.Make3Array(tracks);
            ViewBag.nowM = DateTime.Now.Year + "-" + nowdate;
            return View();
        }

        public IActionResult CreateModal()
        {
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            List<ClassifyDTO> classList = _ITrackSpend_Services.GetClassifyInfoList(UserId);
            ViewBag.incomeList = classList.Where(x => x.IncomeOrExpenses == IncomeOrExpensesEnum.收入).OrderBy(x => x.ClassfyTypeId).ToList();
            ViewBag.expensesList = classList.Where(x => x.IncomeOrExpenses == IncomeOrExpensesEnum.支出).OrderBy(x => x.ClassfyTypeId).ToList();
            return PartialView("_Create");
        }
        public IActionResult EditModal(string TrackSpendId)
        {
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            List<ClassifyDTO> classList = _ITrackSpend_Services.GetClassifyInfoList(UserId);
            ViewBag.incomeList = classList.Where(x => x.IncomeOrExpenses == IncomeOrExpensesEnum.收入).OrderBy(x => x.ClassfyTypeId).ToList();
            ViewBag.expensesList = classList.Where(x => x.IncomeOrExpenses == IncomeOrExpensesEnum.支出).OrderBy(x => x.ClassfyTypeId).ToList();
            ViewBag.model = _ITrackSpend_Services.GetEditTrack(TrackSpendId);
            return PartialView("_Edit");
        }
        public IActionResult ViewClassIcon()
        {
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            List<ClassifyDTO> classList = _ITrackSpend_Services.GetClassifyInfoList(UserId);
            ViewBag.incomeList = classList.Where(x => x.IncomeOrExpenses == IncomeOrExpensesEnum.收入).OrderBy(x => x.ClassfyTypeId).ToList();
            ViewBag.expensesList = classList.Where(x => x.IncomeOrExpenses == IncomeOrExpensesEnum.支出).OrderBy(x => x.ClassfyTypeId).ToList();
            return View("ClassIcon");
        }

        public IActionResult CreateIconModal(string Type, string Type2)
        {
            ViewBag.Type = "新增"+Type+"分類";
            ViewBag.Type2 = (IncomeOrExpensesEnum)Enum.Parse(typeof(IncomeOrExpensesEnum), Type2);
            ViewBag.IconList = _ITrackSpend_Services.GetIconList();
            ViewBag.IconTypeList = _ITrackSpend_Services.GetIconTypeList();

            return PartialView("_CreateIcon");
        }
        [HttpPost]
        public IActionResult CreateClassify([FromBody] ClassIconDTO DTO)
        {
            DTO.UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            if (_ITrackSpend_Services.CreateClassifyInfo(DTO))
            {
                return Json(new { Success = true });
            }
            return Json(new { Success = false });
        }
        [HttpPost]
        public IActionResult CreateTrackSpend([FromBody] TrackSpendDTO DTO)
        {
            DTO.UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            if (_ITrackSpend_Services.CreateTrackSpendInfo(DTO))
            {
                return Json(new { Success = true });
            }
            return Json(new { Success = false });
        }
        [HttpPost]
        public IActionResult EditTrackSpend([FromBody] TrackSpendDTO DTO)
        {
            if (_ITrackSpend_Services.EditTrackSpendInfo(DTO))
            {
                    return Json(new { Success = true });
            }
                return Json(new { Success = false });
        }
        public IActionResult DeleteClassify(int ClassifyId)
        {
            if (_ITrackSpend_Services.DeleteClassifyInfo(ClassifyId))
            {
                return Json(new { Success = true });
            }
            return Json(new { Success = false });
        }
        [HttpPost]
        public IActionResult ViewChart1(string? nowdate)
        {
            if (nowdate == null)
                nowdate = DateTime.Now.Month.ToString();
            else
                nowdate = nowdate.Split("-")[1];
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            object[] result = _ITrackSpend_Services.GetChart1(nowdate, UserId);
            return Json(new { income = result[0], expenses = result[1] });
        }
        [HttpPost]
        public IActionResult ViewChart2(string? nowdate)
        {
            if (nowdate == null)
                nowdate = DateTime.Now.Month.ToString();
            else
                nowdate = nowdate.Split("-")[1];
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            object[] result = _ITrackSpend_Services.GetChat2(nowdate, UserId);
            return Json(new { amount = result[0], note = result[1], color = result[2] });
        }
        public IActionResult ViewChart3(string? nowdate)
        {
            if (nowdate == null)
                nowdate = DateTime.Now.Month.ToString();
            else
                nowdate = nowdate.Split("-")[1];
            long UserId = HttpContext.Session.GetObject<UserSessionDTO>("User").UserId;
            object[] result = _ITrackSpend_Services.GetChart3(nowdate, UserId);
            return Json(new { date = result[0], expenses = result[1], income = result[2], cashsurplus = result[3] });
        }
    }
}

C_Web/C_Web/Areas/TrackSpending/Views/TrackSpend/ClassIcon.cshtml
@using C_Web.Entity.TrackSpend.Enum
@using C_WebDTO.TrackSpendDTO
@{
    List<ClassifyDTO> incomelsit = ViewBag.incomeList;
    List<ClassifyDTO> expenseslist = ViewBag.expensesList;
}


<style>
    #tab-title > div {
        background-color: #BEBEBE;
    }

    #tab-title .active {
        background-color: #ffffff;
    }
</style>

<div class="row">
    <h2 class="modal-title">
        分類管理
    </h2>
</div>
<div style="white-space: nowrap; display:block; align-content:center; justify-content:center;display: inline-flex; flex-wrap:wrap; width:100%">
    <div id="tab-title" style="list-style: none; border:solid; border-radius:5px; ">
        <div style="display: inline-flex; font-size:medium; ">
            <a data-type="@IncomeOrExpensesEnum.支出"
               style="font-weight:bold; text-decoration: none; color: inherit;" href="#expenses">支出</a>
        </div>
        <div style="display: inline-flex; font-size:medium;">
            <a data-type="@IncomeOrExpensesEnum.收入"
               style="font-weight:bold; text-decoration: none; color: inherit;" href="#income">收入</a>
        </div>
    </div>
</div>

<div id="classicontable" class="modal-body">
    <div class="col-xl-12 col-md-12 col-sm-12">
        <div id="income" class="form-control tab-inner container" style="border:solid; border-color:black; margin-top:1%; height:auto; display:flex; flex-wrap:wrap">
            @foreach(var item in incomelsit)
            {
                <div class="col-sm-1">
                    <i style="display:flex; align-items:center; border:none; padding-left:27px; color: @item.TypeColorCode"
                       class="@item.IconCode fa-2x form-control"><i id="deleteclass_@item.ClassifyId" class="bi bi-x-circle" style="font-size:1rem;  margin-bottom: 31px; display:none; color:black"></i></i>
                    <span style="display:flex; align-items:center; border:none; padding-left:27px">@item.ClassifyName</span>
                </div>
            }
        </div>

        <div id="expenses" class="form-control tab-inner container" style="border:solid; border-color:black; margin-top:1%; height:auto; display:flex; flex-wrap:wrap">
            @foreach(var item in expenseslist)
            {
                <div class="col-sm-1">
                    <i style="display:flex; align-items:center; border:none; padding-left:27px; color: @item.TypeColorCode"
                       class="@item.IconCode fa-2x form-control"><i id="deleteclass_@item.ClassifyId" class="bi bi-x-circle" style="font-size:1rem;  margin-bottom: 31px; display:none; color:black"></i></i>
                    <span style="display:flex; align-items:center; border:none; padding-left:27px">@item.ClassifyName</span>
                </div>
            }
        </div>
    </div>
</div>
<hr />
<div class="col-xl-12 col-md-12 col-sm-12" style="margin-bottom:1%; display:flex">
    <div class="col-md-4">
        <button id="CreateIcon" class="btn btn-info form-control">新 增 分 類</button>
    </div>
    <div class="col-md-4 ">
        <button id="deleteclass" class="btn btn-danger form-control">刪 除</button>
    </div>
    <div class="col-md-4 ">
        <a href="/TrackSpending/TrackSpend/Index" class="btn btn-dark form-control">返 回</a>
    </div>
</div>


<!--CreateIcon Modal新增分類-->
<div class="modal fade" id="CreateIconmodal" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
        </div>
    </div>
</div>

<script>
    //#region 支出收入_切換
    $(function () {
        var $li = $("#tab-title div")
        $($li.eq(0).addClass("active").find("a").attr("href")).siblings(".tab-inner").hide();

        $li.click(function () {
            $($(this).find("a").attr("href")).show().siblings(".tab-inner").hide();
            $(this).addClass("active").siblings(".active").removeClass("active");
        });
    })
    //#endregion

    $("#CreateIcon").on("click", function () {
        let type = $(".active").find("a").html().toString();
        let type2 = $(".active").find("a").attr("data-type");
        $("#CreateIconmodal .modal-content").load("@Url.Action("CreateIconModal","TrackSpend")",
        { Type: type,
            Type2: type2,
        });
        $("#CreateIconmodal").modal("show");
    })
    //#region delete
    $(function () { 
        let deleONOFF = true;

        $("[id^=deleteclass_]").on("click", function () { 
            let table = ($(this).parents().parents()[1].id);
            let bool = confirm("是否確認刪除此分類？");
            if (bool) {
                $.post("@Url.Action("DeleteClassify","TrackSpend")", { ClassifyId: parseInt($(this)[0].id.split("_")[1]) }, function (e) {
                    console.log(e);
                    if (e.success) {
                        Swal.fire({
                            icon: "success",
                            title: "成功",
                            text: "刪除完成",
                            showCloseButton: true,
                            backdrop: true,
                        });
                        $("#" + table).load(location.href + " #" + table +">* ", "");
                    }
                    else{
                        Swal.fire({
                            icon: "error",
                            title: "失敗",
                            text: "刪除錯誤",
                            showCloseButton: true,
                            backdrop: true,
                        })
                    }
                })
            }
        })


        $("#deleteclass").on("click", function () {
            if (deleONOFF) {
                $("[id^=deleteclass_]").css("display", "");
                deleONOFF = false;
            }
            else{
                $("[id^=deleteclass_]").css("display", "none");
                deleONOFF = true;
            }  
        })

    })
    //#endregion
</script>

C_Web/C_Web/Areas/TrackSpending/Views/TrackSpend/Index.cshtml
@{
    List<List<List<string>>> tracks = ViewBag.data;
}

<style>

</style>

<div class="container" >
    <div class="row">
        <h2 style="font-weight:bold;">
            記帳本
        </h2>     
        <div id="tab-title" style="display: flex; margin-left: 60%;">
            <input id="searchmonth" type="month" style="margin-right:20%" value="@ViewBag.nowM" />
            <i class="bi bi-pie-chart-fill" style="font-size:2rem; margin-right:20%"><a href="#CHART1"></a></i>
            <i class="bi bi-pie-chart" style="font-size:2rem; margin-right:20%"><a href="#CHART2"></a></i>
            <i class="bi bi-bar-chart-steps" style="font-size:2rem;"><a href="#CHART3"></a></i>
        </div>
    </div>
    <hr />
    <div style="display:block">
        <span id="totalexpenses" style="font-size:larger; color:#F0B524 ; font-weight:bold; text-align:left;"></span>
        <span id="totalincome" style="font-size:larger; color: #12ADCB; font-weight:bold; float:right;"></span>
    </div>
    <div class="col-xl-12 col-md-12 col-sm-12" style="display:flex; justify-content:center; text-align:center">
        <div id="CHART1" class="col-md-5 tab-inner" style="margin: 0 auto">
            <canvas id="spendChart1">
            </canvas>
            <hr />
        </div>
        <div id="CHART2" class="col-md-5 tab-inner" style="margin: 0 auto">
            <canvas id="spendChart2">
            </canvas>
            <hr />
        </div>
        <div id="CHART3" class="col-md-7 tab-inner" style="margin: 0 auto">
            <canvas id="spendChart3">
            </canvas>
            <hr />
        </div>
    </div>
    


    
    <div class="col-xl-12 col-md-12 col-sm-12" style="margin-bottom:1%; display:flex">
        <div class="col-md-6">
            <button id="createTrack" class="btn btn-success form-control">新 增 明 細</button>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("ViewClassIcon","TrackSpend")" class="btn btn-success form-control">分 類 管 理</a>
        </div>
    </div>

    
    <div id="trackstable" class="display:block" style="height: 400px; width: auto; overflow-y: scroll; ">
        <div class="display: block" style="width:auto">

            @for (var x = 0; x < tracks.Count(); x++)
            {
                List<List<string>> conbination = tracks[x];
                <div class="displa: block" style="width:500px; margin: 0 auto; margin-top: 1%; border: solid; border-radius: 10px">
                    @for (var y = 0; y < conbination.Count(); y++)
                    {
                        List<string> strList = conbination[y];
                        if (strList.Count() == 1)
                        {
                            <h2 style="text-align:center">@strList[0]</h2>
                            <hr style="border:solid" />
                        }
                        else{
                            <ul id="track_@strList[5]" style="list-style: none;">
                                <li data-classid="@strList[6]" style="display: flex; justify-content: space-between;">
                                    <div style="display: flex; align-items: center;">
                                        <i class="@strList[0] fa-2x" style="color: @strList[1]; text-align:left">
                                            &thinsp;
                                        </i>
                                        <font class="" style="font-size:larger; font-weight:bold; ">@strList[2]</font>
                                    </div>
                                    @{
                                        strList[3] = strList[4] == "支出" && Convert.ToInt32(strList[3]) != 0 ? "-" + strList[3] : " "+strList[3];
                                    }
                                    <div style="display: flex; align-items: center; margin-right: 3%">
                                        <span style="white-space:nowrap; "><i class="fas fa-coins fa-lg" style="margin-right: 10%"></i><font class="amount" style="font-size:medium; font-weight:bold;">@strList[3]</font></span>
                                    </div>
                                </li>
                                <hr />
                            </ul>
                        }
                    } 
                </div>
            }
        </div>
    </div>
</div>

<!--Create Modal新增-->
<div class="modal fade" id="Createmodal" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">

        </div>
    </div>
</div>
<!--Edit Modal修改-->
<div class="modal fade" id="Editmodal" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">

        </div>
    </div>
</div>
   

<script>
    $("#createTrack").on("click", function () { 
        $("#Createmodal .modal-content").load("@Url.Action("CreateModal","TrackSpend")");
        $("#Createmodal").modal("show");
    });
    $(function () {
        $("#searchmonth").on("change", function (e) {
            // console.log($("#searchmonth").val()); 
            ch1($("#searchmonth").val());
            ch2($("#searchmonth").val());
            ch3($("#searchmonth").val());
            $("#trackstable").load("/TrackSpending/TrackSpend?nowdate=" + $("#searchmonth").val() + " #trackstable>*", "", 
            function () {
                tracktotal();
                trackclick();
            });
        })
    })

    //#region 圖表_切換
    $(function () {
        var $li = $("#tab-title i")  //jq 取id tan-title的對象 底下的i標籤
        $($li.eq(0).addClass("active").find("a").attr("href")).siblings(".tab-inner").hide("fast"); // 預設將取得的對象底下第一位[0]添加active的class屬性後, 找到其餘所有a標籤href對象內容隱藏

        $li.click(function () {  //監聽click事件 變更 添加or移除active 實現切換
            $($(this).find("a").attr("href")).show().siblings(".tab-inner").hide();
            $(this).addClass("active").siblings(".active").removeClass("active");
        });
    })
    //#endregion

    //#region 收入支出 結算
    $(function () {
        tracktotal();
    })
    function tracktotal() {
        let IN = 0;
        let EX = 0;
        let str = $(".amount");
        str.each(function (e) {
            // console.log(parseInt(str[e].innerHTML));
            let num = parseInt(str[e].innerHTML);
            if (num >= 0)
                IN += num;
            else
                EX += num;
        })
        $("#totalexpenses").text("支出: " + EX);
        $("#totalincome").text("收入: " + IN);
    }
    //#endregion

    //#region chart
    $(function(){
        ch1();
        ch2();
        ch3();
    })
    //#region chart1
    function ch1(date) {
        $.post("@Url.Action("ViewChart1","TrackSpend")", { nowdate: date }, function (e) {
            // console.log([e.expenses[0], e.income[0]]);
            let preChart1 = Chart.getChart("spendChart1");
            if (preChart1)
                preChart1.destroy();
            var ctx = document.getElementById("spendChart1").getContext('2d');
            var spendChart = new Chart(ctx, {
                type: "doughnut",
                data: {
                    labels: ["支出", "收入",],
                    datasets: [{
                        label: "金額: ",
                        data: [e.expenses[0], e.income[0]],
                        backgroundColor: [
                            "#F0B524",
                            "#12ADCB",
                        ],
                        borderColor: "#000000",
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            ticks: {
                                beginAtZero: true
                            }
                        }
                    }
                }
            })
        })
    }
    //#endregion

    //#region chart2
    function ch2(date) {
        $.post("@Url.Action("ViewChart2","TrackSpend")", { nowdate: date }, function (e) {
            // console.log(e.amount);
            // console.log(e.note);
            // console.log(e.color);
            let preChart2 = Chart.getChart("spendChart2");
            if (preChart2)
                preChart2.destroy();
            var ct = document.getElementById("spendChart2").getContext('2d');
            var spendChart2 = new Chart(ct, {
                type: "doughnut",
                data: {
                    labels: e.note,
                    datasets: [{
                        label: "金額: ",
                        data: e.amount,
                        backgroundColor: e.color,
                        borderColor: "#000000",
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            ticks: {
                                beginAtZero: true
                            }
                        }
                    }
                }
            })
        })
    }
    //#endregion

    //#region chart3
    function ch3(date) {
        $.post("@Url.Action("ViewChart3","TrackSpend")", { nowdate: date }, function (e) {
            // console.log(e.date);
            // console.log(e.expenses);
            // console.log(e.income);
            // console.log(e.cashsurplus);
            let preChart3 = Chart.getChart("spendChart3");
            if (preChart3)
                preChart3.destroy();
            var ct = document.getElementById("spendChart3").getContext('2d');
            var spendChart2 = new Chart(ct, {
                type: "bar",
                data: {
                    labels: e.date,
                    datasets: [{
                        label: "收入: ",
                        data: e.income,
                        backgroundColor: "#12ADCB",
                        borderColor: "#12ADCB",
                        showLine: true
                    },
                    {
                        label: "支出: ",
                        data: e.expenses,
                        backgroundColor: "#F0B524",
                        borderColor: "#F0B524",
                        showLine: true
                    },
                    {
                        label: "結餘: ",
                        data: e.cashsurplus,
                        backgroundColor: "#F98282",
                        borderColor: "#F98282",
                        showLine: true
                    }
                    ]
                },
                options: {
                    indexAxis: "y",
                },
                scales: {
                    y: {
                        ticks: {
                            beginAtZero: true
                        },
                        position: "top"
                    }
                }
            })
        })
    }
    //#endregion

    //#endregion

    //#region edit
    $(function () {
        $("[id^=track_]").on("click", function () {
            let ID = $(this)[0].id.split("_")[1];
            console.log(ID);
            $("#Editmodal .modal-content").load("@Url.Action("EditModal","TrackSpend")", { TrackSpendId: ID });
            $("#Editmodal").modal("show");
        })
    })
    function trackclick(){
        $("[id^=track_]").on("click", function () {
            let ID = $(this)[0].id.split("_")[1];
            console.log(ID);
            $("#Editmodal .modal-content").load("@Url.Action("EditModal","TrackSpend")", { TrackSpendId: ID });
            $("#Editmodal").modal("show");
        })
    }
    //#endregion
</script>

C_Web/C_Web/Areas/TrackSpending/Views/TrackSpend/_CreateIcon.cshtml
@{
    var iconlist = ViewBag.IconList;
    var icontypelist = ViewBag.IconTypeList;
}

<div class="modal-header">
    <h2 class="modal-title">
        @ViewBag.Type
    </h2>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>

<div class="modal-body">
    <div class="col-xl-12 col-md-12 col-sm-12">
        <div class="form-group col-md-12">
            <span><i></i></span><input type="text" id="newclassifyName" class="form-control" placeholder="請輸入自定義名稱" maxlength="5"/>
        </div>
        <div class="form-control" style=" border:solid; border-color:black; margin-top:3%; height:auto; display:flex; flex-wrap:wrap">
            @foreach (var item in icontypelist)
            {
                <div class="col-sm-2" style="margin-top:1%">
                    <div data-color="@item.TypeColorCode" data-val="@item.Icon_TypeId"
                             style="border:solid; border-radius:10px; padding-left:18px;
                            display:flex; align-items:center; font-size:small; width:4em;" class="TYPEITEM">
                        @item.TypeName
                    </div>
                </div>
            }
        </div>
 
        <div class="form-control" style="border:solid; border-color:black; margin-top:3%; height:auto; display:flex; flex-wrap:wrap">
            @foreach(var item in iconlist)
            { 
                <div class="col-sm-2"> 
                    <i data-val="@item.IconId" 
                    style="display:flex; align-items:center; border:none; padding-left:27px" 
                    class="@item.IconCode fa-2x form-control ICON"></i>
                </div>
            }
        </div>
    </div>
</div>

<div class="modal-footer">
    <button data-type="@ViewBag.Type2" id="createClass" class="btn btn-primary col-12" style="font-weight:bold">送 出</button>
</div>

<script>
    $(function () {
        let classIcon = "", classColor = "";
    })
    $(".ICON").on("click", function () { 
        $(".ICON").css("border", "none");  //動態修改style參數
        $(this).css("border", "solid");
        classIcon = $(this).attr("data-val");
    })
    $(".TYPEITEM").on("click", function () { 
        $(".TYPEITEM").css("background-color", "#fff");
        $(".TYPEITEM").css("color", "#495057");
        $(".TYPEITEM").css("font-weight", "normal");
        $(".ICON").css("color", "#495057");
        let typecolor = $(this).attr("data-color");
        $(this).css("background-color", typecolor);
        $(this).css("color", "#fff");
        $(this).css("font-weight", "bold");
        $(".ICON").css("color", typecolor);
        classColor = $(this).attr("data-val");
    })
    function error(obj) {
        Swal.fire({
            icon: "error",
            title: "失敗",
            text: obj,
            showCloseButton: true,
            backdrop: true,
        })
    }
    //#region create
    $("#createClass").on("click", function () { 
        let table = $(this).attr("data-type");
        if ($("#newclassifyName").val() == "" || $("#newclassifyName").val() == null) {
            error("名稱不得為空");
            return false;
        }
        if(classIcon == ""){
            error("請選擇圖示");
            return false;
        }
        if (classColor == "") {
            error("請選擇分類");
            return false;
        }
        else{
            fetch("@Url.Action("CreateClassify","TrackSpend")", {
                method: "POST",
                body: JSON.stringify({
                    ClassName: $("#newclassifyName").val(),
                    ClassIcon: parseInt(classIcon),
                    ClassColor: parseInt(classColor),
                    InOrEx: $(this).attr("data-type"),
                }),
                headers: new Headers({
                    "Content-Type": "application/json",
                }),
            })
            .then((res) => {
                return res.json();
            }).then((resjson) => {
                if (resjson.success) {
                    $("#CreateIconmodal").modal("hide");
                    location.reload();
                    // if(table == "支出")
                    //     $("#expenses").load(location.href+" #expenses>*", "");
                    // else
                    //         $("#income").load(location.href + " #income>*", "");
                    Swal.fire({
                        icon: "success",
                        title: "成功",
                        text: "新增完成",
                        showCloseButton: true,
                        backdrop: true,
                    });
                }
                else {
                    Swal.fire({
                        icon: "error",
                        title: "失敗",
                        text: "新增錯誤",
                        showCloseButton: true,
                        backdrop: true,
                    })
                }
            })
        }
    })
    //#endregion
</script>